name: Daily Heat Push

on:
  schedule:
    - cron: '0 1,3,5,7 * * *'  # 每天台灣時間 9、11、13、15 點
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-driver
          pip install selenium requests

      - name: Run main.py
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
        run: python main.py
