name: Manual Heat Push

on:
  workflow_dispatch:  # ✅ 改成只允許手動執行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-driver
          pip install selenium requests

      - name: Run push script
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
        run: python main.py
